---
tasks:
- name: init
  short: i
  script: bash scripts/githook.sh
  description: setup git hooks
  usage: setup git hooks
  require:
    exec:
    - bash
- name: fmt
  description: format the go code
  usage: format the go code
  script: bash scripts/fmt.sh
  require:
    exec:
    - bash
    - gofumpt
    - git
- name: vet
  short: v
  description: go vet
  usage: go vet
  script: go vet ./...
  require:
    exec:
    - go
- name: lint
  short: l
  description: lint the go code
  usage: lint the go code
  script: golangci-lint run
  require:
    exec:
    - golangci-lint
- name: test
  short: t
  description: test
  usage: test
  script: bash scripts/test.sh
