---
name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.2'
    - run: go mod download
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.31 # don't specify patch version
    - name: test
      run: bash scripts/test.sh
